apiVersion: v1
kind: Service
metadata:
  name: interop-datalark-service
  labels:
    nginx: pod
spec:
  type: ClusterIP
  selector:
    nginx: datalark
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888